### ISSUE TITLE
Help with AD5144A library

### ISSUE THREAD

**Issue by Manhem** [RobTillaart/AD5144A#1]
Please do if you have the time to help me create a library for AD5144A.
I have the hardware so I can test it for you.

For full discusion see:
https://github.com/RobTillaart/Arduino/issues/170

Thanks

**Comment by RobTillaart** [comment]
First I need to read the datasheet, might take some time.

**Comment by RobTillaart** [comment]
Created a develop branch - https://github.com/RobTillaart/AD5144A/tree/develop

- functional far from complete 
- may still contain copy/paste bugs (to have an initial version fast)
- has basic write and read functions (async only)
- minimal tested, 
- has an example sketch that compiles on an UNO.
- has some basic CI (copied like a lot of things)
- has initial readme.md file 


please give it a try.
- in the example sketch you still have to set the I2C address  
- please report your testresults.

**Comment by RobTillaart** [comment]
added a performance example; (enough for today)

**Comment by RobTillaart** [comment]
fixed a blocking thing in the constructor. sketches now give some output ...

**Comment by Manhem** [comment]
Hi.
Thanks.
I'm going to test this on monday. Going to be away over the weekend.
I give you an answer in the beginning of next week.
I download the files just before I shall test it if you are doing more changes.

**Comment by RobTillaart** [comment]
Sounds like a plan,

There are these items on my list if time permits
- synchronous update of all (4) potmeters at once.
- check out the EEPROM part as I think that defines reboot values (important)
- read the datasheet in more detail to check for interesting functionality.
- check the datasheet to see if I missed a type that also supports I2C (easy)
- update readme.md a bit more
- some refactor e,g, return values, abstract the I2C part (to make it easier to derive a SPI version)

**Comment by RobTillaart** [comment]
develop branch updated 
- sync update added (not tested)
- EEPROM done
- refactored
- 70% functional complete  (see todo remarks in .h file)

**Comment by RobTillaart** [comment]
Continued apparently in #2
