### ISSUE TITLE
5142A differences notes. (Top scale command)

### ISSUE THREAD

**Issue by grahas** [RobTillaart/AD5144A#15]
Just a random note but I think the command for the top scale data bits for the 5142A and 5144A are flipped. In the 5142A datasheet, command 12 data bits are
Top scale
D0 = 0; normal mode
D0 = 1; shutdown mode
https://www.analog.com/media/en/technical-documentation/data-sheets/AD5122A_5142A.pdf page 24

vs the AD5144A
Top scale
D0 = 1; enter
D0 = 0; exit
https://www.analog.com/media/en/technical-documentation/data-sheets/ad5124_5144_5144a.pdf page 29

**Comment by grahas** [comment]
feel free to close it when ever you read it.

**Comment by RobTillaart** [comment]
@grahas
Thanks for pointing out this difference,
I did a quick compare of all the mentions of "top scale" in both datasheets and they seem to be identical. It looks like **ADS5122/42 PDF** is incorrect as the naming normal and shutdown does not make sense in context of the top scale. 
I added the term "top scale" to the issue title so it could be found a bit easier later if needed.
