### ISSUE TITLE
implementing AD5144 library 

### ISSUE THREAD

**Issue by RobTillaart** [RobTillaart/AD5144A#2]
Add unit tests if possible

**Comment by Manhem** [comment]
Faulty report #1 
Hi.
I have now tried a little.
- If I in the loop put AD.write(val, 0) I can use AD.read to get the value back (only reads it from storage the value in AD5144A not reading directly from the AD5144)
- If I use AD.readBackRDAC(val) I get 255 back.
- If I in Setup use AD.zeroAll I get 127 back from AD.read and 255 back from AD..readBackRDAC(val)
- I can use AD.pmCount and get 4 back.
It seems that I can not get the AD5144 to move to a new value.

I have one more thing I shall try but I don't think that works because I can read some values.
Right now I have a I2C-splitter between the CPU and AD5144.
But I have a display that works.

Another thing is that the CPU I use right now is a ATSAMD21G18A.
I don't know if that's the problem.
You can find it in the Arduino IDE

Hope this can help you a little.
More tests comes tomorrow.

**Comment by RobTillaart** [comment]
Will dive into this tomorrow
- [x] **AD.read()** behaves as intended and expected.
- [x] **AD.readBackRDAC(val)** => can you post the code you use?
- [x] **AD.zeroAll()** should set internal cache to all zero's (to be checked)
- [x] **pmCount()** returns the number of potmeters in the device so 4 seems OK.
- [x] **I2C splitter**  ??? - might relate to next point
- [x] **ATSAMD21G18A** is that a 3V3 device?  some I2C devices are not too tolerant ...

**Comment by Manhem** [comment]
Hi.
The I2C splitter is a TCA9548 and works well for all other things.
All the components are made for 3.3V.

I have verified that pmCount() is oK. A change the value in .cpp and I get the right answer back.

Here are the code that I'm using right now to test with.
I have put in the display and I2C splitter.
The splitter I need, but even if I remove the display it the same thing.
I hope this can help you.
I'm going to do some more tests today and see if I can find anything.

```cpp
#include <Wire.h>

#include "TCA9548A.h"
TCA9548A * i2cSplitter;

#include <SSD1803a_I2C.h>
const byte i2caddr  = 0x3c;
SSD1803a_I2C lcd(i2caddr);

#include "AD5144A.h"
AD5144A AD(0x77);

void setup()
{
  Serial.begin(9600);
  
  Wire.begin();

  // Init TCA9584A
  i2cSplitter = new TCA9548A(0x74);
  
  // Start up the I2C splitter
  i2cSplitter -> begin(Wire);             // Wire instance is passed to the library
  i2cSplitter -> closeAll();              // Set a base state which we know (also the default state on power on)
//  i2cSplitter -> openChannel(0);          // Open up channel 0 (can be 0-7)
  i2cSplitter -> openChannel(1);          // Open up channel 0 (can be 0-7)
  i2cSplitter -> openChannel(2);          // Open up channel 0 (can be 0-7)

  lcd.begin(16, 4);
  lcd.setCursor(4,0); lcd.print("hello world");
  lcd.setCursor(0,1); lcd.print("Hello world");
  lcd.setCursor(0,2); lcd.print("Hello World");
  lcd.setCursor(0,3); lcd.print("HELLO WORLD");  

  // turn on light on display
  digitalWrite(10, true);
  digitalWrite(9, true);

AD.begin();
AD.zeroAll();
}


void loop()
{
  if (AD.begin() == false)
  {
    Serial.println("device not found");
    return;
  }

Serial.println(AD.pmCount());

  for (int p = 0; p < AD.pmCount(); p++)
  {
    for (int val = 0; val < 150; val++)
    {
      delay(100);
      AD.write(p, val);
      if (AD.read(p) != val)
      {
        Serial.print("error:\t");
        Serial.print(p);
        Serial.print("\t");
        Serial.print(val);
        Serial.println();
      }
Serial.println(AD.readBackRDAC(p));
    }
Serial.print("+");    
  }
  Serial.println("done...");

delay(5000);
}
```

**Comment by RobTillaart** [comment]
Can you replace the call to **AD.begin()** with
```cpp
  if (AD.begin() == false)
  {
    Serial.println("device not found");
    return;
  }
```
to check the device is seen on the I2C bus.

I will first extend the number of basic examples to get some decent coverage of the functionality.
(is in progress)

**Comment by RobTillaart** [comment]
BTW
Pin 20 = Write Protect.
Optional Write Protect. This pin prevents any changes to the present RDAC and EEPROM content, except when reloading the content of the EEPROM into the RDAC register. WP is activated at logic low. If this pin is not used, tie WP to VLOGIC.

By any chance pin connected or floating?

**Comment by RobTillaart** [comment]
issue #1 and #2 got mixed => closed the other one.

**Comment by RobTillaart** [comment]
I have added examples, no changes in the library core so far.

Can you run them ?

please start with 
- **AD5144A_test_control_register.ino** and post the output
-  **AD5144A_test_write.ino** 
- **AD5144A_low_level.ino**  // this is not a library test, just the minimal set of Wire calls 

thanks,

**Comment by Manhem** [comment]
Hi
Here are the result for the jury....
My chip don't have the WP-pin.

//Bosse
From Sweden

AD5144A_test_control_register.ino:
check datasheet
CH	WP	EE	MODE	BURST
0	1	2	4	8
1	1	2	4	8
2	1	2	4	8
3	1	2	4	8
done...


AD5144A_test_write.ino:
0	0	0	0	255
0	0	1	0	255
0	0	2	0	255
0	0	3	0	255
50	0	0	50	255
50	0	1	50	255
50	0	2	50	255
50	0	3	50	255
100	0	0	100	255
100	0	1	100	255
100	0	2	100	255
100	0	3	100	255
150	0	0	150	255
150	0	1	150	255
150	0	2	150	255
150	0	3	150	255
200	0	0	200	255
200	0	1	200	255
200	0	2	200	255
200	0	3	200	255
250	0	0	250	255
250	0	1	250	255
250	0	2	250	255
250	0	3	250	255
done...

AD5144A_low_level.ino:
LOOP 0..255 POTMETER 3
0	0
1	0
2	0
.
.
255  0

**Comment by RobTillaart** [comment]
Hi
1. we can exclude the hardware write protect. 
2. AD5144A_test_control_register.ino
(observation) The control registers all seem to be high. 
This is not expected as the default bits should be  xxxx0011.
See table. 

![image](https://user-images.githubusercontent.com/462844/117000069-ce604700-ace0-11eb-9499-18ae5e3bd769.png)

3. AD5144A_test_write.ino
(columns) value ... Write ... rdac ... read() ... readBackRDAC()
- val, rdac, read() as expected.
- The write all return 0 which means false => think....  need to make the return value more informative.
- readBackRDAC() returns all 0xFF - seems consistent with (2) above

I updated **AD5144A_low_level.ino** a bit
Will be an update in ~10 minutes of the .cpp file

**Comment by RobTillaart** [comment]
OK, found a bug in the send() and readBack() functions
instead of using _wire-> I used Wire which is definitely incorrect (but it kept the compiler happy)

It explains why the isConnected() did not fail

fixed this in the AD5144A.cpp file - CI test is runnning - 
added some print statements in send and readBack => those will be removed. asap.

Please test the above 3 examples again....

(Netherlands, near Eindhoven)

**Comment by Manhem** [comment]
Here are the new answer:
AD5144A_test_control_register:
SEND cmd: 1 val: 1
check datasheet
CH	WP	EE	MODE	BURST
READBACK cmd: 1 val: 1 TX: 0
0	1	2	4	8
READBACK cmd: 1 val: 1 TX: 0
1	1	2	4	8
READBACK cmd: 1 val: 1 TX: 0
2	1	2	4	8
READBACK cmd: 1 val: 1 TX: 0
3	1	2	4	8
done...

AD5144A_test_write:
SEND cmd: 1 val: 1
0	SEND cmd: 1 val: 1
0	0	0	READBACK cmd: 1 val: 1 TX: 0
255
0	SEND cmd: 1 val: 1
0	1	0	READBACK cmd: 1 val: 1 TX: 0
255
0	SEND cmd: 1 val: 1
0	2	0	READBACK cmd: 1 val: 1 TX: 0
255
0	SEND cmd: 1 val: 1
0	3	0	READBACK cmd: 1 val: 1 TX: 0
255
50	SEND cmd: 1 val: 1
0	0	50	READBACK cmd: 1 val: 1 TX: 0
255
50	SEND cmd: 1 val: 1
0	1	50	READBACK cmd: 1 val: 1 TX: 0
255
50	SEND cmd: 1 val: 1
0	2	50	READBACK cmd: 1 val: 1 TX: 0
255
50	SEND cmd: 1 val: 1
0	3	50	READBACK cmd: 1 val: 1 TX: 0
255
100	SEND cmd: 1 val: 1
0	0	100	READBACK cmd: 1 val: 1 TX: 0
255
100	SEND cmd: 1 val: 1
0	1	100	READBACK cmd: 1 val: 1 TX: 0
255
100	SEND cmd: 1 val: 1
0	2	100	READBACK cmd: 1 val: 1 TX: 0
255
100	SEND cmd: 1 val: 1
0	3	100	READBACK cmd: 1 val: 1 TX: 0
255
150	SEND cmd: 1 val: 1
0	0	150	READBACK cmd: 1 val: 1 TX: 0
255
150	SEND cmd: 1 val: 1
0	1	150	READBACK cmd: 1 val: 1 TX: 0
255
150	SEND cmd: 1 val: 1
0	2	150	READBACK cmd: 1 val: 1 TX: 0
255
150	SEND cmd: 1 val: 1
0	3	150	READBACK cmd: 1 val: 1 TX: 0
255
200	SEND cmd: 1 val: 1
0	0	200	READBACK cmd: 1 val: 1 TX: 0
255
200	SEND cmd: 1 val: 1
0	1	200	READBACK cmd: 1 val: 1 TX: 0
255
200	SEND cmd: 1 val: 1
0	2	200	READBACK cmd: 1 val: 1 TX: 0
255
200	SEND cmd: 1 val: 1
0	3	200	READBACK cmd: 1 val: 1 TX: 0
255
250	SEND cmd: 1 val: 1
0	0	250	READBACK cmd: 1 val: 1 TX: 0
255
250	SEND cmd: 1 val: 1
0	1	250	READBACK cmd: 1 val: 1 TX: 0
255
250	SEND cmd: 1 val: 1
0	2	250	READBACK cmd: 1 val: 1 TX: 0
255
250	SEND cmd: 1 val: 1
0	3	250	READBACK cmd: 1 val: 1 TX: 0
255
done...



AD5144A_low_level
LOOP 0..255 POTMETER 2
0	0
1	0
2	0
.
.
255  0

**Comment by RobTillaart** [comment]
so 
- **_wire->write(...)** seems to return 1 as it should 
- **_wire->endTransmission()** returns 0 as it should. 

==> remove those debug prints, and dig deeper...

**Comment by RobTillaart** [comment]
removed the print statements, and added one for the requestFrom() method. 
(was not checked yet)

Please do only **AD5144A_test_write()**  (you may shorten the loop)

**Comment by Manhem** [comment]
AD5144A_test_write.ino:
0	0	0	0	requerstFrom cmd: 0255
0	0	1	0	requerstFrom cmd: 0255
0	0	2	0	requerstFrom cmd: 0255
0	0	3	0	requerstFrom cmd: 0255
50	0	0	50	requerstFrom cmd: 0255
50	0	1	50	requerstFrom cmd: 0255
50	0	2	50	requerstFrom cmd: 0255
50	0	3	50	requerstFrom cmd: 0255
done...

**Comment by Manhem** [comment]
Continue tomorrow?
You can think over the night.

**Comment by RobTillaart** [comment]
I have two other issues (and a project to build, and 2 kids, one with a broken phone) so sometimes it takes a bit longer.

**Comment by RobTillaart** [comment]
Where does  the "requerstFrom " text come from?
It is not in my example...

**Comment by RobTillaart** [comment]
Can you do a I2C bus scan with - https://github.com/RobTillaart/MultiSpeedI2CScanner

starts with a help page, the command you should send is   **ps**

Just to see if the device is visible...

**Comment by Manhem** [comment]
The  "requerstFrom " I have put in there so you know from where the log is coming from.
I test your scanner tomorrow.
I have already use the "i2c_scanner" you can find under Wire example to scan the I2C bus, but I will run yours also.

**Comment by Manhem** [comment]
Now I saw that you have update the .cpp.
The things a send you was with the old code and my modification.

**Comment by RobTillaart** [comment]
to be continued tomorrow (unless I get a bright moment :)

**Comment by Manhem** [comment]
Hi.
DON'T DO ANYTHING MORE RIGHT NOW.
MAYBE I HAVE FOUND A BIG PROBLEM IN MY DESIGN.
I WILL GET BACK TO YOU.

But I have run your I2C scanner and found this:
<print=found>
TIME	DEC	HEX		50	100	150	200	250	300	350	400	[KHz]
--------------------------------------------------------------------------------------------------------
57396	33	0x21		V	V	V	V	V	V	V	V (TCA9555 I/O expander)
57413	60	0x3C		V	V	V	V	V	V	V	V (DOGS164W Display)
57421	72	0x48		V	V	V	V	V	V	V	V (LTC2991 
57424	73	0x49		V	V	V	V	V	V	V	V (LTC2991 
57429	80	0x50		V	V	V	V	V	V	V	V (M24M02 Memory)
57432	81	0x51		V	V	V	V	V	V	V	V (M24M02 Memory)
57434	82	0x52		V	V	V	V	V	V	V	V (M24M02 Memory)
57436	83	0x53		V	V	V	V	V	V	V	V (M24M02 Memory)
57440	88	0x58		V	V	V	V	V	V	V	V (M24M02 Memory)
57442	89	0x59		V	V	V	V	V	V	V	V (M24M02 Memory)
57444	90	0x5A		V	V	V	V	V	V	V	V (M24M02 Memory)
57446	91	0x5B		V	V	V	V	V	V	V	V (M24M02 Memory)
57461	116	0x74		V	V	V	V	V	V	V	V (TCA9548 I2C Splitter)
57464	119	0x77		V	V	V	V	V	V	V	V (AD5144 Digital potentiometer)

**Comment by RobTillaart** [comment]
> DON'T DO ANYTHING MORE RIGHT NOW.
> MAYBE I HAVE FOUND A BIG PROBLEM IN MY DESIGN.
> I WILL GET BACK TO YOU.

Good morning, what a way to wake up ;)
Success analyzing

**Comment by Manhem** [comment]
Hi.
I just want to tell you how it goes.
I can now see the right I2C address when I'm doing a scan.
But I have still one more problem that I have not solved yet.
It's not your fault.....
I'm coming back when I have solved the second problem and tested your library.

**Comment by RobTillaart** [comment]
Having the right I2C address is an important step !
Stay positive, you can do it!  :)

**Comment by Manhem** [comment]
Hi.
I'm back.
I have now get in contact with the AD5144 but I think I have some problem with you library.
I have run a test where I but in 0 - 150 into AD5144.
If I read AD.read() I get the right number back of cource, but if I use AD.readBackRDAC() I get this back.

0-requerstFrom cmd: 10
1-requerstFrom cmd: 11
2-requerstFrom cmd: 12
6-requerstFrom cmd: 16
7-requerstFrom cmd: 17
8-requerstFrom cmd: 18
9-requerstFrom cmd: 19
10-requerstFrom cmd: 110
11-requerstFrom cmd: 111
12-requerstFrom cmd: 112
98-requerstFrom cmd: 198
99-requerstFrom cmd: 199
100-requerstFrom cmd: 1100
101-requerstFrom cmd: 1101

And so on.
Is it your library??
So let's get on with some tests.

**Comment by RobTillaart** [comment]
Welcome back !

during development there are only problems with libraries :)

**AD.read(idx)** will return the number from a cache, this number must be the same. I'm caching it for performance.

**AD.readBackRDAC(idx)** does an actual read over I2C from the device register.

> Is it your library??

You added the "requerstFrom " somewhere and I must see the actual code to be able to diagnose. 

Please send me the (compressed) output of **AD5144A_low_level.ino**
It does not use the library, but mimics the lowest level IO the library does.
If we get that to work, I know (probably) how to fix the library.

**Comment by Manhem** [comment]
Hi
This was easy:
CONNECT:	0
LOOP 0..255 POTMETER 0
0	0
1	0
2	0
3	0
 And so on, all the way

**Comment by RobTillaart** [comment]
CONNECT 0 means the device is seen on the bus. (good)
 
Also the writing to the device returns a 0 so it is send ...
Can you measure with a multimeter if the resistance changes (between wiper pin and A or B)?

Maybe the write does work, but the readbackRDAC just doesn't....

**Comment by Manhem** [comment]
I'm coming back to you.
Have one more issue that I must solve.

**Comment by RobTillaart** [comment]
BTW, I want to mention you as coauthor of the library to give credits where they are due.
Are you ok with that ? 
If so, what name to use?

**Comment by Manhem** [comment]
Let's see if we can get it to work first.
I haven't got the time to test it yet.
So be patient...

**Comment by RobTillaart** [comment]
A thought

Could it be that the send command should send the bytes in different order?   line 185-200

current code (simplified)
```cpp
uint8_t AD51XX::send(const uint8_t cmd, const uint8_t value)
{
  // COMMAND 1 - page 20
  _wire->beginTransmission(_address);
  _wire->write(cmd); 
  _wire->write(value); 
  return _wire->endTransmission();
}
```

should be 
```cpp
uint8_t AD51XX::send(const uint8_t cmd, const uint8_t value)
{
  // COMMAND 1 - page 20
  _wire->beginTransmission(_address);
  _wire->write(value);       
  _wire->write(cmd); 
  return _wire->endTransmission();
}
```

**Comment by Manhem** [comment]
Hi.
It seems that I have got it to work, but I need more tests.
The first code is right. If I try the second one I get lots of strange answers.
I will be back...

**Comment by Manhem** [comment]
Hi again.
Now I have a question for you.
Do you have time and want a challenge?
I have found some code for LTC2991 and now I only need to learn how I2C is working.
But if you have time......

**Comment by Manhem** [comment]
AD5144
All the test so far is good, but I want to make more tests.

**Comment by RobTillaart** [comment]
> AD5144
> All the test so far is good, but I want to make more tests.

So no changes needed to the library?  then I can merge the code into master branch...

Are there any things people should know , things you learned about the AD5144 etc?

**Comment by Manhem** [comment]
Please do not move it yet.
Give me some more days so I can test everything.
Right now I have only tested to right and read from AD5144.
I shall try to write to memory and see if I can read it back and some more things.

**Comment by RobTillaart** [comment]
> Hi again.
> Now I have a question for you.
> Do you have time and want a challenge?
> I have found some code for LTC2991 and now I only need to learn how I2C is working.
> But if you have time......

Can you provide a link?
Not so much time as I have some projects to do (to earn a living)

**Comment by RobTillaart** [comment]
> Please do not move it yet.
> Give me some more days so I can test everything.
> Right now I have only tested to right and read from AD5144.
> I shall try to write to memory and see if I can read it back and some more things.

OK,

**Comment by Manhem** [comment]
LTC2991.
I send you the link tomorrow.
I have it on another computer in an other place.

**Comment by RobTillaart** [comment]
Created an empty I2C framework for the LTC - https://github.com/RobTillaart/LTC2991
Please  follow up here - https://github.com/RobTillaart/LTC2991/issues/1

**Comment by RobTillaart** [comment]
Typed a lot for the LTC2991 library this evening, 
- interface (.h) is sort of complete => All registers have get/set access functions 
- interface (.h) need a refactor for datatypes (esp too much flags are bool )
- implementation (.cpp) needs a lot of code, 70% is just placeholder..
- examples need to be written.

**Comment by Manhem** [comment]
Hi.
I have now done some more tests with read and write to EEprom and with this first test it is working.
So if you like to put it ready, you can do that but no guarantees... there can still be some bugs that I haven't found yet.

**Comment by RobTillaart** [comment]
OK,
- no tagged release yet. 
- will update readme.md,  keywords.txt and meta data 
- will add issues for some missing functions
- 

Advantage of the merge into the master is that other people can start using the lib, add their comments and fixes etc.

**Comment by RobTillaart** [comment]
Everything is in the master branch now

**Comment by RobTillaart** [comment]
@Manhem 
just to inform you a 0.1.1 version is in progress to implement **setTopScale()** and **clrTopScale()** functions.

**Comment by RobTillaart** [comment]
created 0.1.2 version that implements linearMode and potentiometerMode + increment decrement.

created an issue to update readme.md + keywords.txt

**Comment by RobTillaart** [comment]
As no remarks are made I am going to release this one. 
Please report newly found bugs in separate issues as  "creating" the library can be considered done.

**Comment by Manhem** [comment]
Hi.
I'm now going to put everything together, but AD5144 and LTC2991 and see what happends.
Can take some time.
If I find anything I let you know.
