### ISSUE TITLE
Success story with AD5142A 256 position dual digital pot

### ISSUE THREAD

**Issue by patfelst** [RobTillaart/AD5144A#27]
Hi Rob,

Just wanted to report I have this working with a AD5142A. I've only used the .begin() and .write() functions on both pots, but it worked great first go.

This is on an ESP32 (M5Stack Core2) with a magnetometer. The two pots give real world heading feedback, 180-deg out of phase so one "wiper" is always in the centre when the other one is at the min/max.

I wasn't 100% sure how to target the first I2C bus (Wire) on the Core2. It uses Wire1 (second I2C bus) for internal stuff like the power management chip. I ended up doing this and it worked.

```c++
// Create digital pot object
AD5142A AD(0x2F, &Wire);
```
then in setup()
```c++
  Wire.begin(EXT_I2C_SDA, EXT_I2C_SCL);

  // Initialise digital potentiometers
  if (AD.begin() == false) {
    Serial.println("AD5142A Dual Digital Pot NOT FOUND");
  } else {
    Serial.println("AD5142A Dual Digital pot FOUND!");
  }
```
and in loop()
```c++
  // Update the pots
  AD.write(POT1, pot1_val);
  AD.write(POT2, pot2_val);
```
Thanks very much for the library!

**Comment by RobTillaart** [comment]
@patfelst 
Good to hear it works at first go.
Such feedback is valuable as it is almost impossible to test all possible boards and configurations.
Thanks for reporting.
